name: Helm Workflow

on:
  workflow_call:

jobs:
  helm:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        role-to-assume: ${{ secrets.AWS_GITHUB_ROLE }}
        role-session-name: helm-session
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Install Helm
      uses: azure/setup-helm@v3
      with:
        version: v3.11.3

    - name: Build and Push Helm Chart
      env:
        ECR_REGISTRY: ${{ secrets.AWS_ECR_REGISTRY }}
      run: |
        helm package python-app
        helm push neeraj-helm-0.0.1.tgz oci://$ECR_REGISTRY/

