name: Python Application CI/CD

on:
  push:
    branches:
      - main
  workflow_dispatch:


permissions:
  id-token: write
  contents: read

jobs:
  test:
    name: Run Tests
    uses: ./.github/workflows/test.yaml
    with:
      python-version: "3.10"

  security:
    name: Run Security Scan
    uses: ./.github/workflows/security.yaml

  docker:
    name: Build and Publish Docker Image
    uses: ./.github/workflows/docker.yaml
    needs:
      - test
      - security
    secrets: inherit
    with:
      image_tag: latest

  helm:
    name: Build and Publish Helm Chart
    needs:
      - test
      - security
    uses: ./.github/workflows/helm.yaml
    secrets: inherit

  deploy_dev:
    name: Deploy App to Dev Env
    uses: ./.github/workflows/deploy.yaml
    needs:
      - docker
      - helm
    secrets: inherit
    with:
      image_tag: latest
      namespace: dev
      environment: dev

  deploy_prod:
    name: Deploy App to Prod Env
    uses: ./.github/workflows/deploy.yaml
    needs: deploy_dev
    secrets: inherit
    with:
      image_tag: latest
      namespace: prod
      environment: prod