name: Python Application CI/CD

on: workflow_dispatch

permissions:
  id-token: write
  contents: read

jobs:
  # 1. Test, Security, Docker, and Helm jobs
  test:
    uses: ./.github/workflows/test.yaml

  security:
    uses: ./.github/workflows/security.yaml
    needs: test

  docker:
    uses: ./.github/workflows/docker.yaml
    needs: security

  helm:
    uses: ./.github/workflows/helm.yaml
    needs: docker


