name: Python Application CI/CD

on:
  push:
    branches:
      - main
  workflow_dispatch:


permissions:
  id-token: write
  contents: read

jobs:
  # 1. Test, Security, Docker, and Helm jobs
  test:
    uses: ./.github/workflows/test.yaml
    with:
      python-version: "3.10"

  security:
    uses: ./.github/workflows/security.yaml
    needs: test

  docker:
    uses: ./.github/workflows/docker.yaml
    needs: security
    secrets: inherit
    with:
      image_tag: latest

  helm:
    uses: ./.github/workflows/helm.yaml
    needs: docker
    secrets: inherit

  deploy_dev:
    uses: ./.github/workflows/deploy.yaml
    needs: helm
    secrets: inherit
    with:
      image_tag: latest
      namespace: dev
      environment: dev