on:
  workflow_call:

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v4

    - name: Cache Trivy Vulnerability Database
      uses: actions/cache@v3
      with:
        path: ~/.cache/trivy
        key: ${{ runner.os }}-trivy-db
        restore-keys: |
          ${{ runner.os }}-trivy-db

    - name: Scan Dependencies for Vulnerabilities
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        severity: 'CRITICAL'
        exit-code: 1
        ignore-unfixed: true
        cache-dir: ~/.cache/trivy

    - name: Scan Dockerfile for Misconfigurations
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'config'
        severity: 'CRITICAL'
        exit-code: 1
        cache-dir: ~/.cache/trivy
