name: Security Workflow

on:
  workflow_call:

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v4

    - name: Install Trivy (Vulnerability Scanner)
      run: |
        wget -qO- https://github.com/aquasecurity/trivy/releases/latest/download/trivy_Linux-64bit.tar.gz | tar zxv
        sudo mv trivy /usr/local/bin/

    - name: Verify Trivy Installation
      run: trivy --version

    - name: Scan Dependencies
      run: trivy fs --exit-code 1 --severity HIGH,CRITICAL .

    - name: Scan Dockerfile
      run: trivy config .
